# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b9960193bcdede55a4ade357a3eda101cbe73b32b6704cc85a762fd2be930f4c3c5c0a6331089df47f7e9577fc408b0629d0117b63ec444bd4b5f30503397a2

test:
  secret_key_base: 5bfe214c9c0a92c07bd108c8adef8a215fb3915bf9520917a7a089ab8032fe679f8d58a896b5eb841e644836ec2a9cb143ed6030fb04ab640a23fac05ace8675

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
